# Generated by Django 3.0 on 2020-01-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameLender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
