# Generated by Django 3.0 on 2020-01-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameLender', '0002_genr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='test',
        ),
    ]
